export type CityKey =
  | "beijing"
  | "shenzhen"
  | "guangzhou"
  | "shanghai"
  | "tianjin"
  | "wuhan"
  | "hangzhou"
  | "suzhou"
  | "chengdu"
  | "chongqing"
  | "xian"
  | "nanjing"
  | "common";

export type KnowledgeSource = {
  title: string;
  url: string;
};

export type KnowledgeTable = {
  headers: string[];
  rows: string[][];
};

export type KnowledgeSection = {
  id: string;
  city: CityKey;
  category: string;
  title: string;
  summary: string;
  details?: string[];
  table?: KnowledgeTable;
  formula?: string[];
  note?: string;
  sources?: KnowledgeSource[];
  resources?: KnowledgeSource[];
  keywords?: string[];
};

export const knowledgeMeta = {
  title: "全国与城市二手房交易知识库",
  release: "2026.07.16-decision-r1",
  schemaVersion: "2.0.0",
  asOfDate: "2026-07-16",
  monitoringStatus: "validated_snapshot",
  monitoredSources: 57,
  decisionRules: 70,
  goldenCases: 348,
  validationAssertions: 4159,
};

export const cities = [
  {
    key: "beijing" as const,
    name: "北京",
    code: "110000",
    version: "bj@2025-12-24.1",
    effectiveFrom: "2025-12-24",
    status: "五环内限购 · 五环外放宽",
    keyInput: "五环内 / 五环外",
    commercialDown: "首套 15% · 二套 20%",
    providentDown: "首套 20% · 二套 25%",
    accent: "#8f5d3b",
  },
  {
    key: "shenzhen" as const,
    name: "深圳",
    code: "440300",
    version: "sz@2026-04-30.1",
    effectiveFrom: "2026-04-30",
    status: "核心区限购 · 分区判断",
    keyInput: "区 + 宝安街道",
    commercialDown: "首套 15% · 二套 20%",
    providentDown: "首套 20% · 二套 20%",
    accent: "#376f63",
  },
  {
    key: "guangzhou" as const,
    name: "广州",
    code: "440100",
    version: "gz@2024-09-30.1",
    effectiveFrom: "2024-09-30",
    status: "居民住房限购已取消",
    keyInput: "住房套数仍影响税贷",
    commercialDown: "首套 15% · 二套 15%",
    providentDown: "首套 20% · 二套 20%",
    accent: "#536a9f",
  },
  {
    key: "shanghai" as const,
    name: "上海",
    code: "310000",
    version: "sh@2026-02-26.1",
    effectiveFrom: "2026-02-26",
    status: "外环分区限购 · 另有房产税",
    keyInput: "外环内外 + 居住年限",
    commercialDown: "首套 15% · 二套 20%/25%",
    providentDown: "首套 20% · 二套 20%/25%",
    accent: "#9a514d",
  },
  {
    key: "tianjin" as const,
    name: "天津",
    code: "120000",
    version: "tj@2026-02-01.1",
    effectiveFrom: "2026-02-01",
    status: "全市不限购 · 贷款按区认定",
    keyInput: "目标区住房套数",
    commercialDown: "首套 15% · 二套 15%",
    providentDown: "首套 20% · 二套 20%",
    accent: "#4d7180",
  },
  {
    key: "wuhan" as const,
    name: "武汉",
    code: "420100",
    version: "wh@2025-09-30.1",
    effectiveFrom: "2025-09-30",
    status: "全市不限购 · 公积金三价取低",
    keyInput: "成交/评估/计税三价",
    commercialDown: "全国底线 15% · 银行确认",
    providentDown: "首套 20% · 二套 30%",
    accent: "#506b8a",
  },
  {
    key: "hangzhou" as const,
    name: "杭州",
    code: "330100",
    version: "hz@2024-10-09.1",
    effectiveFrom: "2024-10-09",
    status: "全市不限购 · 积分不作购房资格",
    keyInput: "目标区 + 挂牌状态",
    commercialDown: "全国底线 15% · 银行确认",
    providentDown: "首套 20% · 二套 20%",
    accent: "#4f806d",
  },
  {
    key: "suzhou" as const,
    name: "苏州",
    code: "320500",
    version: "su@2026-06-01.1",
    effectiveFrom: "2026-06-01",
    status: "不限购不限售 · 县级市分流",
    keyInput: "区 / 县级市",
    commercialDown: "最低 15% · 银行确认",
    providentDown: "首套/二套 15%（限期）",
    accent: "#70834d",
  },
  {
    key: "chengdu" as const,
    name: "成都",
    code: "510100",
    version: "cd@2026-03-25.1",
    effectiveFrom: "2026-03-25",
    status: "不限购 · 取得证后可上市",
    keyInput: "查询日期 + 房屋性质",
    commercialDown: "全国底线 15% · 银行确认",
    providentDown: "首套 20%（截至年末）",
    accent: "#9a7047",
  },
  {
    key: "chongqing" as const,
    name: "重庆",
    code: "500000",
    version: "cq@2026-02-09.1",
    effectiveFrom: "2026-02-09",
    status: "不限购 · 主城房产税试点",
    keyInput: "目标区 + 房屋类型",
    commercialDown: "全国底线 15% · 银行确认",
    providentDown: "首套/二套 20%",
    accent: "#8b584c",
  },
  {
    key: "xian" as const,
    name: "西安",
    code: "610100",
    version: "xa@2025-07-31.1",
    effectiveFrom: "2025-07-31",
    status: "不限购 · 双公积金中心分流",
    keyInput: "缴存管理中心",
    commercialDown: "全国底线 15% · 银行确认",
    providentDown: "省中心首套 20% · 再次 25%",
    accent: "#8b6748",
  },
  {
    key: "nanjing" as const,
    name: "南京",
    code: "320100",
    version: "nj@2026-04-16.1",
    effectiveFrom: "2026-04-16",
    status: "不限购不限售 · 保障房专门流转",
    keyInput: "普通商品房 / 保障房",
    commercialDown: "全国底线 15% · 银行确认",
    providentDown: "首套/二套 20%",
    accent: "#6d5e8b",
  },
];

const nationalTaxSources: KnowledgeSource[] = [
  {
    title: "财政部等三部门：房地产市场税收政策公告",
    url: "https://szs.mof.gov.cn/zhengcefabu/202411/t20241113_3947450.htm",
  },
  {
    title: "财政部、税务总局：个人销售住房增值税政策",
    url: "https://fgk.chinatax.gov.cn/zcfgk/c102416/c5246356/content.html",
  },
  {
    title: "财政部、税务总局：换购住房个人所得税退税政策",
    url: "https://szs.mof.gov.cn/zhengcefabu/202601/t20260104_3981159.htm",
  },
  {
    title: "税务机关：满五唯一的家庭与地域口径",
    url: "https://tianjin.chinatax.gov.cn/11200000000/0300/030005/20221205085925789.shtml",
  },
  {
    title: "财政部、税务总局：个人住房印花税和土地增值税优惠",
    url: "https://zhejiang.chinatax.gov.cn/art/2008/10/22/art_8409_14513.html",
  },
];

const nationalPropertySources: KnowledgeSource[] = [
  {
    title: "全国人大常委会公报：《中华人民共和国民法典》",
    url: "https://wb.flk.npc.gov.cn/flfg/PDF/bd53dd912c1048f2aecbaa229238334b.pdf",
  },
  {
    title: "市场监管总局：《中华人民共和国城市房地产管理法》",
    url: "https://www.samr.gov.cn/zfjcj/tzgg/art/2023/art_d334f021ed52443d970cd58d934a3a6c.html",
  },
  {
    title: "住建部、市场监管总局：规范房地产经纪服务的意见",
    url: "https://www.samr.gov.cn/zw/zfxxgk/fdzdgknr/jjjzs/art/2023/art_54ae47e32a87445ba0aae5c4fa36709c.html",
  },
  {
    title: "国家发展改革委、财政部：不动产登记收费标准",
    url: "https://zfxxgk.ndrc.gov.cn/web/iteminfo.jsp?id=19843",
  },
];

const nationalFinanceSources: KnowledgeSource[] = [
  {
    title: "人民银行、金融监管总局：个人住房贷款最低首付政策",
    url: "https://www.nfra.gov.cn/cn/view/pages/ItemDetail.html?docId=1180751&generaltype=1&itemId=861",
  },
  {
    title: "中国人民银行：取消全国层面个人住房贷款利率政策下限",
    url: "https://www.pbc.gov.cn/goutongjiaoliu/113456/113469/2025092212554091417/index.html",
  },
  {
    title: "中国人民银行：下调个人住房公积金贷款利率",
    url: "https://app.www.gov.cn/govdata/gov/202505/07/528461/article.html",
  },
];

const shanghaiSources: KnowledgeSource[] = [
  { title: "上海 2026 年房地产政策", url: "https://www.shanghai.gov.cn/nw31406/20260227/961ca351f504470f90ff4d3d001bb613.html" },
  { title: "上海商业贷款首付政策", url: "https://www.shanghai.gov.cn/cmsres/85/85a76ed299344c8e8875c634a5d40112/c76d21c1fb0591c2337efe54fa2f4677.pdf" },
  { title: "上海 2026 年公积金通知与问答", url: "https://www.shanghai.gov.cn/xbhygq/20260228/87e93e4c373c4bfe81af5557a77d2e70.html" },
];

const tianjinSources: KnowledgeSource[] = [
  { title: "天津取消住房限购政策解读", url: "https://www.tj.gov.cn/zwgk/zcjd/202410/t20241016_6754085.html" },
  { title: "天津 2026 年公积金政策", url: "https://www.tj.gov.cn/sy/tjxw/202601/t20260127_7232106.html" },
  { title: "天津直管公产住房使用权规则", url: "https://ghhzrzy.tj.gov.cn/yshj/yhyshjxzspzdggzt/zcfg3/bdcdjn/tjszcwjbdc/202404/t20240412_6598188.html" },
];

const wuhanSources: KnowledgeSource[] = [
  { title: "武汉取消住房限购通知", url: "https://zgj.wuhan.gov.cn/zwdt/tzgg/202309/t20230928_2273274.shtml" },
  { title: "武汉公积金二手房贷款指南", url: "https://gjj.wuhan.gov.cn/bsfw/ywzl/ywzn/dkyw/202412/t20241219_2504837.html" },
  { title: "武汉公积金 2025 年年度报告", url: "https://gjj.wuhan.gov.cn/zwgk/ndbg/202603/t20260326_2745342.html" },
];

const hangzhouSources: KnowledgeSource[] = [
  { title: "杭州全面取消住房限购政策", url: "https://www.hzarchives.org.cn/info/12166" },
  { title: "杭州公积金政策文件", url: "https://gjj.hangzhou.gov.cn/attach/0/ea4c9466f14b4d749ddc7e385e747900.pdf" },
  { title: "杭州居住证积分管理规则", url: "https://police.hangzhou.gov.cn/art/2024/8/14/art_1229436763_4290774.html" },
];

const suzhouSources: KnowledgeSource[] = [
  { title: "苏州住房政策回顾与现行口径", url: "https://www.suzhou.gov.cn/2025ndzt/fjxsd/202601/37a3fd39b7464851b0ecc266a9fea2d8.shtml" },
  { title: "苏州公积金 15% 首付通知", url: "https://www.suzhou.gov.cn/szsrmzf/bmwj/202508/49c061c990664ccf997a9a56aebe0933.shtml" },
  { title: "苏州 2026 年公积金额度政策", url: "https://www.suzhou.gov.cn/szsrmzf/dstx/202605/d7bf7a1d2f55450db7a81f3b48883fa6.shtml" },
];

const chengduSources: KnowledgeSource[] = [
  { title: "四川住建厅转载成都取消购房资格审核", url: "https://jst.sc.gov.cn/scjst/cjfdcscpwjkfz/2024/4/29/bf2d4d6577f94b15ac7a04feda6f0a31.shtml" },
  { title: "成都住房取得产权证后可上市", url: "https://news.chengdu.cn/2024/1015/2448438.shtml" },
  { title: "成都 2026 年阶段性公积金政策", url: "https://www.news.cn/20260324/e4548eb47b1741c5a8d4aedff49136a5/c.html" },
];

const chongqingSources: KnowledgeSource[] = [
  { title: "重庆住房公积金贷款指南", url: "https://www.cqgjj.cn/ywzn/gjjdkzn/2653.htm" },
  { title: "重庆个人住房房产税试点政策", url: "https://www.cq.gov.cn/zwgk/zfxxgkml/szfwj/xzgfxwj/szfbgt/202505/t20250527_14659500_app.html" },
  { title: "重庆财政局房产税政策解读", url: "https://czj.cq.gov.cn/zwgk_268/zfxxgkml/zcjd/bmjd/202505/t20250523_14650218.html" },
];

const xianSources: KnowledgeSource[] = [
  { title: "西安取消住房限购政策公开报道", url: "https://news.bjd.com.cn/2024/05/09/10768000.shtml" },
  { title: "陕西省住房资金管理中心贷款政策", url: "https://www.sxgjj.com/info/1333/13575.htm" },
  { title: "西安住房公积金管理中心现行利率", url: "https://zfgjj.xa.gov.cn/gzdt/tzgg/1920023668442849281.html" },
];

const nanjingSources: KnowledgeSource[] = [
  { title: "南京全市取消普通住房购房证明", url: "https://fcj.nanjing.gov.cn/dtxx/mtdt/202309/t20230908_4005817.html" },
  { title: "南京取消商品住房限售", url: "https://sw.nanjing.gov.cn/ywdd/yqjj/202504/t20250401_5108134.html" },
  { title: "南京公积金额度调整", url: "https://gjj.nanjing.gov.cn/zwgk/tzgg/202510/t20251009_5662167.html" },
];

export const sections: KnowledgeSection[] = [
  {
    id: "common-decision-package",
    city: "common",
    category: "决策规则包",
    title: "12 城购房资格与精确税费规则已机器化",
    summary: "叙述性政策之外，新增可供 AI、Agent 和规则执行器直接读取的 JSON 决策包；资格、税费、缺失输入、证据和版本均可追溯。",
    table: {
      headers: ["城市", "资格结构", "城市资格规则", "核定个税默认率", "决策包版本"],
      rows: [
        ["北京", "五环内外 + 户籍/工作居住证 + 社保个税 + 多子女", "13 条", "需主管税务机关确认", "bj@2025-12-26.decision.1"],
        ["深圳", "核心区 / 放宽区 / 无审核区 + 居住证", "12 条", "1%（广东规则）", "sz@2026-04-30.decision.1"],
        ["广州", "居民普通商品住房取消普遍限购", "2 条", "1%（广东规则）", "gz@2024-09-30.decision.1"],
        ["上海", "外环内外 + 户籍 + 社保个税 + 居住证年限", "13 条", "1%（上海税务）", "sh@2026-02-26.decision.1"],
        ["天津", "居民普通商品住房取消普遍限购", "2 条", "需主管税务机关确认", "tj@2024-10-16.decision.1"],
        ["武汉", "居民普通商品住房取消普遍限购", "2 条", "需主管税务机关确认", "wh@2023-09-19.decision.1"],
        ["杭州", "居民普通商品住房取消普遍限购", "2 条", "需主管税务机关确认", "hz@2024-05-09.decision.1"],
        ["苏州", "居民普通商品住房取消普遍限购", "2 条", "需主管税务机关确认", "su@2024-01-01.decision.1"],
        ["成都", "居民普通商品住房取消普遍限购", "2 条", "需主管税务机关确认", "cd@2024-04-29.decision.1"],
        ["重庆", "普通商品住房一般路径 + 持有房产税分流", "2 条", "需主管税务机关确认", "cq@2024-09-01.decision.1"],
        ["西安", "居民普通商品住房取消普遍限购", "2 条", "需主管税务机关确认", "xa@2024-05-09.decision.1"],
        ["南京", "普通商品住房一般路径 + 保障房分流", "2 条", "需主管税务机关确认", "nj@2023-09-08.decision.1"],
      ],
    },
    details: [
      "统一输入 Schema 区分城市/区域、家庭资格套数、契税家庭套数、房屋面积与性质、卖方持有年限、三种价格和税费承担约定。",
      "统一输出 eligible / ineligible / conditional / unknown / out_of_scope，并返回规则 ID、证据 ID、政策版本、缺失输入和逐项计算轨迹。",
      "全国税费包覆盖契税、增值税、附加、个人所得税、个人住房印花税和土地增值税；上海、重庆个人住房房产税单列为持有环节。",
      "只有主管税务机关接受的计税价格与必要参数完整时才给精确金额；地方核定个税率没有官方依据时强制追问，不统一猜成 1%。",
      "已物化 348 个黄金场景，覆盖 12 城资格正反例、140㎡、满2年、满5年、套数上限、生效日前后和关键输入缺失，共通过 4,159 项断言。",
    ],
    formula: [
      "增值税（持有不足2年）= 税务计税价格 ÷ 1.03 × 3%",
      "核实个税 = max(0, 不含增值税收入 − 原值 − 可扣税金 − 合理费用) × 20%",
      "买方交易现金税费 = 买方本人税费 + 合同明确由买方承担的卖方税费",
    ],
    note: "网页仍是知识展示与轻量检索，不提供交互计算器；Agent 应读取机器包并在输入不足时追问。",
    resources: [
      { title: "机器可读发布清单 manifest.json", url: "./data/transaction-decision/manifest.json" },
      { title: "场景输入 JSON Schema", url: "./data/transaction-decision/schemas/scenario.schema.json" },
      { title: "规则 JSON Schema", url: "./data/transaction-decision/schemas/rule.schema.json" },
      { title: "输出 JSON Schema", url: "./data/transaction-decision/schemas/evaluation.schema.json" },
      { title: "黄金场景覆盖摘要", url: "./data/transaction-decision/test-summary.json" },
    ],
    sources: nationalTaxSources,
    keywords: ["决策规则", "精确税费", "机器可读", "JSON Schema", "Agent", "RAG", "348", "4159", "unknown", "out_of_scope"],
  },
  {
    id: "bj-eligibility",
    city: "beijing",
    category: "购房资格",
    title: "北京商品住房资格决策",
    summary: "北京仍需购房资格核验。先判断五环位置，再判断户籍、家庭住房套数、连续社保或个税年限及多子女情况。",
    table: {
      headers: ["买方类型", "五环内", "五环外", "规则 ID"],
      rows: [
        ["京籍家庭", "最多 2 套", "不限套数", "BJ-ELIG-001"],
        ["京籍成年单身", "按京籍家庭执行", "不限套数", "BJ-ELIG-002"],
        ["京籍二孩及以上家庭", "基础上增加 1 套", "不限套数", "BJ-ELIG-003"],
        ["非京籍家庭/成年单身", "五环内无房且社保/个税 ≥2 年，可购 1 套", "社保/个税 ≥1 年，不限套数", "BJ-ELIG-004"],
        ["非京籍二孩及以上家庭", "基础上增加 1 套", "满足基础年限后不限套数", "BJ-ELIG-005"],
        ["港澳台侨家庭", "北京无房且境内工作、学习和居留，可购 1 套自住", "同左", "BJ-ELIG-006"],
        ["符合条件外籍家庭", "北京无房，可购 1 套自住", "同左", "BJ-ELIG-007"],
      ],
    },
    details: [
      "京籍包括本市户籍、驻京部队现役军人和现役武警，以及持有效北京市工作居住证的家庭。",
      "家庭成员通常包括夫妻双方及未成年子女；购房资格通过不代表具体房屋一定可以过户。",
      "查询 2025-08-09 至 2025-12-23 的历史交易，应切换到 bj@2025-08-09.1。",
    ],
    note: "北京住建委页面可能同时残留历史条件，现行判断以当前汇总段和有效规范性文件为准。",
    sources: [
      {
        title: "北京市住建委购房资格核验页面",
        url: "https://zjw.beijing.gov.cn/bjjs/fdcjy/gfzg87/index.shtml",
      },
      {
        title: "京建发〔2025〕565号",
        url: "https://www.beijing.gov.cn/gate/big5/www.beijing.gov.cn/zhengce/zhengcefagui/202512/t20251225_4361661.html",
      },
    ],
    keywords: ["京籍", "非京籍", "五环", "工作居住证", "二孩", "社保", "个税"],
  },
  {
    id: "bj-transfer",
    city: "beijing",
    category: "房屋可交易性",
    title: "北京标的房屋转让核验",
    summary: "购房资格和房屋可交易性是两道独立判断。产权、查封、抵押、共有关系或房屋性质不清时，统一返回 conditional。",
    details: [
      "核验产权证、权利人、共有权人同意、查封和异议登记。",
      "央产房、经济适用房、共有产权住房、限价房、人才房等特殊产权必须转专项规则。",
      "住宅平房也需要购房资格核验；赠与、继承和共有份额转让适用不同资格规则。",
    ],
    note: "BJ-TRANSFER-001：普通商品住房只有完成登记条件核验后，才能从 conditional 转为 eligible。",
    sources: [
      {
        title: "北京市住建委购房资格与常见问答",
        url: "https://zjw.beijing.gov.cn/bjjs/fdcjy/gfzg87/index.shtml",
      },
    ],
    keywords: ["央产房", "经济适用房", "共有产权", "查封", "抵押", "住宅平房"],
  },
  {
    id: "bj-financing",
    city: "beijing",
    category: "贷款与首付",
    title: "北京商业贷款与公积金",
    summary: "政策最低首付不等于最终首付。合同价、银行评估价、授信额度、房龄和借款人收入都会改变实际资金需求。",
    table: {
      headers: ["项目", "现行口径", "规则 ID"],
      rows: [
        ["商贷首套最低首付", "15%", "BJ-LOAN-COM-001"],
        ["商贷二套最低首付", "20%", "BJ-LOAN-COM-002"],
        ["公积金首套最低首付", "20%", "BJ-LOAN-PF-001"],
        ["公积金二套最低首付", "25%", "BJ-LOAN-PF-002"],
        ["公积金首套基础最高额度", "120 万元", "BJ-LOAN-PF-003"],
        ["公积金二套基础最高额度", "100 万元", "BJ-LOAN-PF-004"],
        ["缴存年限对应额度", "每缴存 1 年可贷 15 万元", "BJ-LOAN-PF-005"],
        ["公积金利率", "首套 2.1%/2.6%；二套 2.525%/3.075%", "BJ-LOAN-PF-006"],
        ["基础缴存", "连续缴存半年及以上，申请时账户正常", "BJ-LOAN-PF-007"],
        ["未结清贷款", "夫妻名下有未还清公积金贷款，不可再次申请", "BJ-LOAN-PF-008"],
        ["离婚一年内", "2017-03-24 及以后离婚，一年内申请按二套政策", "BJ-LOAN-PF-009"],
        ["还款能力", "月均还款额不超过申请人月收入 60%", "BJ-LOAN-PF-010"],
      ],
    },
    details: [
      "商业贷款利率定价不再区分首套、二套，但首付和授信认定仍然存在。",
      "二手房公积金期限受借款人年龄与房屋剩余年限双重限制，并不得超过最高可抵押价值。",
      "绿色建筑、装配式建筑、超低能耗建筑和特定区域支持可能上浮额度；多项同时满足时按现行规则取最有利口径，不应自动叠加。",
    ],
    sources: [
      {
        title: "北京住房公积金贷款业务问答",
        url: "https://gjj.beijing.gov.cn/web/zwfw5/1747335/1747338/743726795/index.html",
      },
      {
        title: "京建发〔2024〕400号",
        url: "https://www.beijing.gov.cn/gate/big5/www.beijing.gov.cn/zhengce/zhengcefagui/202501/t20250109_3984746.html",
      },
    ],
    keywords: ["首付", "商贷", "公积金", "贷款额度", "月供", "评估价"],
  },
  {
    id: "bj-tax",
    city: "beijing",
    category: "税率税费",
    title: "北京买卖双方税费",
    summary: "买方主要为契税；卖方主要判断增值税和个人所得税。法定纳税人与合同约定的实际承担人必须分开。",
    table: {
      headers: ["税种", "法定纳税人", "现行判断", "规则 ID"],
      rows: [
        ["契税", "买方", "唯一/二套 ≤140㎡ 为 1%；唯一 >140㎡ 为 1.5%；二套 >140㎡ 为 2%；其他一般 3%", "BJ-TAX-DEED-001"],
        ["增值税", "卖方", "取得不足 2 年按 3% 征收率；满 2 年免征", "BJ-TAX-VAT-001"],
        ["个人所得税", "卖方", "核实征收为应纳税所得额 ×20%；满五唯一免征", "BJ-TAX-IIT-001"],
        ["增值税附加", "卖方", "仅在产生增值税时计算，以申报系统为准", "BJ-TAX-SUR-001"],
        ["印花税", "买卖双方", "个人买卖住房暂免征收", "NAT-TAX-STAMP-001"],
        ["土地增值税", "卖方", "个人销售住房暂免征收", "NAT-TAX-LAT-001"],
      ],
    },
    details: [
      "北京的满五唯一按北京市范围核验卖方及配偶名下住房，不只看出售人本人。",
      "2026-01-01 至 2027-12-31，卖旧后一年内在北京买新且满足产权人等条件，可申请全部或部分退还已缴住房个税。退税是后续事项，不在到账前冲减交易现金。",
    ],
    note: "不知道计税价格时只能给税率和公式；不知道卖方原值时，不得统一按成交价 1% 估算个税。",
    sources: nationalTaxSources,
    keywords: ["契税", "增值税", "个税", "满二", "满五唯一", "140平方米"],
  },
  {
    id: "bj-inputs",
    city: "beijing",
    category: "必填信息",
    title: "北京最少需要追问什么",
    summary: "关键输入缺失时，Agent 应追问而不是输出虚假精确结论。",
    details: [
      "房屋位于五环内还是五环外。",
      "买方户籍/工作居住证、家庭结构、家庭住房套数、连续社保或个税月数。",
      "房屋性质、产权状态、建筑面积、合同价、计税价和银行评估价。",
      "卖方取得日期、是否满二、是否满五唯一、原值与合法扣除凭证。",
      "满五唯一需核验卖方本人及配偶在北京市的住房套数；拟申请换购退税时，还需旧房出售和新房购买日期、金额、城市及产权人。",
      "公积金需补充缴存月数、账户状态、收入、既往贷款、离婚日期、房龄和可抵押价值。",
      "贷款方式、银行实际批贷额度、中介费用和税费承担约定。",
    ],
    keywords: ["缺失输入", "追问", "五环", "原值", "评估价"],
  },
  {
    id: "sz-zones",
    city: "shenzhen",
    category: "区域分类",
    title: "深圳必须先确定区域",
    summary: "深圳不能只输入城市名。宝安区还必须精确到是否属于新安街道。",
    table: {
      headers: ["区域类型", "范围", "代码"],
      rows: [
        ["核心区", "福田区、南山区、宝安区新安街道", "core"],
        ["放宽区", "罗湖、宝安除新安、龙岗、龙华、坪山、光明", "relaxed"],
        ["无资格审核区", "盐田区、大鹏新区", "no_review"],
      ],
    },
    note: "只知道房屋在宝安区时，购房资格应返回 unknown 并追问街道。",
    sources: [
      {
        title: "深圳 2025 年分区优化政策",
        url: "https://www.sz.gov.cn/cn/xxgk/zfxxgj/zwdt/content/post_12365285.html",
      },
    ],
    keywords: ["福田", "南山", "新安街道", "盐田", "大鹏", "宝安"],
  },
  {
    id: "sz-eligibility",
    city: "shenzhen",
    category: "购房资格",
    title: "深圳商品住房资格决策",
    summary: "2026-04-30 起，符合条件家庭在核心区增加一套指标；有效深圳经济特区居住证可为部分非深户家庭提供核心区一套资格。",
    table: {
      headers: ["买方家庭", "核心区", "放宽区", "盐田/大鹏", "规则 ID"],
      rows: [
        ["深户家庭", "最多 3 套", "不限套数", "不审核、不限套数", "SZ-ELIG-001"],
        ["非深户，社保/个税 ≥1 年", "最多 2 套", "不限套数", "不审核、不限套数", "SZ-ELIG-002"],
        ["非深户，未满 1 年但有有效居住证", "最多 1 套", "最多 2 套", "不审核、不限套数", "SZ-ELIG-003"],
        ["非深户，未满 1 年且无有效居住证", "不可购买", "最多 2 套", "不审核、不限套数", "SZ-ELIG-004"],
      ],
    },
    details: [
      "成年单身人士按居民家庭执行。",
      "核心区 3 套/2 套是 2025 年基础上限与 2026 年增购 1 套政策的合并结果。",
      "普通二手商品住房按分区资格条件判断，不进入统一积分排序；新房意向登记、保障性住房配售、入户积分和学位积分是其他政策场景。",
      "查询 2025-09-06 至 2026-04-29 时，应使用 sz@2025-09-06.1。",
    ],
    sources: [
      {
        title: "深建字〔2026〕86号",
        url: "https://zjj.sz.gov.cn/xxgk/tzgg/content/post_12759895.html",
      },
      {
        title: "深圳 2025 年分区优化政策",
        url: "https://www.sz.gov.cn/cn/xxgk/zfxxgj/zwdt/content/post_12365285.html",
      },
    ],
    keywords: ["深户", "非深户", "居住证", "社保", "核心区", "限购"],
  },
  {
    id: "sz-transfer",
    city: "shenzhen",
    category: "房屋可交易性",
    title: "深圳普通商品住房转让",
    summary: "商品住房和商务公寓的一般转让限制已经取消，但特殊产权房不能直接套用。",
    details: [
      "普通商品住房仍需核验产权登记、查封、抵押、共有关系、租赁和用途。",
      "安居型商品房、人才住房、共有产权住房和其他保障性住房返回 conditional。",
      "未取得完整产权或补缴价款、补缴税费条件不清时必须专项核验。",
    ],
    note: "SZ-TRANSFER-001：取消一般转让限制不等于所有深圳房屋均可自由出售。",
    sources: [
      {
        title: "深圳优化房地产市场政策措施",
        url: "https://www.sz.gov.cn/cn/xxgk/zfxxgj/zwdt/content/post_11580619.html",
      },
    ],
    keywords: ["转让限制", "安居房", "人才房", "共有产权", "商务公寓"],
  },
  {
    id: "sz-financing",
    city: "shenzhen",
    category: "贷款与首付",
    title: "深圳商业贷款与公积金",
    summary: "商贷首套/二套最低首付为 15%/20%；公积金首套和二套均为 20%，2026 年提高基础额度并增加多类上浮。",
    table: {
      headers: ["项目", "现行口径", "规则 ID"],
      rows: [
        ["商贷首套最低首付", "15%", "SZ-LOAN-COM-001"],
        ["商贷二套最低首付", "20%", "SZ-LOAN-COM-002"],
        ["公积金首套/二套最低首付", "20% / 20%", "SZ-LOAN-PF-001/002"],
        ["保障性住房最低首付", "15%", "SZ-LOAN-PF-003"],
        ["单人基础最高额度", "70 万元", "SZ-LOAN-PF-004"],
        ["共同申请基础最高额度", "130 万元", "SZ-LOAN-PF-005"],
        ["单位职工缴存", "连续、按时、足额缴存 6 个月，账户正常", "SZ-LOAN-PF-006"],
        ["灵活就业缴存", "连续 12 个月且累计不少于 36 个月", "SZ-LOAN-PF-007"],
        ["账户余额倍数", "符合条件申请人账户余额合计 ×16", "SZ-LOAN-PF-008"],
        ["还款能力", "等额本息月还款额不超过缴存基数合计 50%", "SZ-LOAN-PF-009"],
        ["三年未提取", "连续 3 年以上未提取可提高 10%，仍受封顶", "SZ-LOAN-PF-010"],
      ],
    },
    details: [
      "购买首套住房额度可上浮 60%；初婚初育 +50%；二孩及以上 +70%；保障性住房 +40%。",
      "初婚初育和二孩及以上同时满足时只选择 50% 或 70%，不叠加。",
      "基础最高额度、余额倍数、还款能力、可贷比例和抵押物限制需同时满足；最高额度不是实际获批额度。",
    ],
    sources: [
      {
        title: "深建字〔2026〕86号",
        url: "https://zjj.sz.gov.cn/xxgk/tzgg/content/post_12759895.html",
      },
      {
        title: "深圳公积金贷款管理补充规定",
        url: "https://zjj.sz.gov.cn/csml/zcfg/xxgk/yshjgg/content/post_12126441.html",
      },
      {
        title: "深圳公积金贷款额度计算问答",
        url: "https://zjj.sz.gov.cn/hdjl/ywzs/gjj/content/post_12798776.html",
      },
    ],
    keywords: ["首付", "公积金", "上浮", "多子女", "初婚初育", "贷款额度"],
  },
  {
    id: "sz-tax",
    city: "shenzhen",
    category: "税率税费",
    title: "深圳买卖双方税费",
    summary: "深圳与北京、广州适用同一套全国住房契税优惠和 2026 年住房销售增值税规则。",
    table: {
      headers: ["税种", "法定纳税人", "现行判断", "规则 ID"],
      rows: [
        ["契税", "买方", "唯一/二套 ≤140㎡ 为 1%；唯一 >140㎡ 为 1.5%；二套 >140㎡ 为 2%；其他一般 3%", "SZ-TAX-DEED-001"],
        ["增值税", "卖方", "不足 2 年按 3% 征收率；满 2 年免征", "SZ-TAX-VAT-001"],
        ["个人所得税", "卖方", "所得额 ×20%；满五唯一免征；核定口径由深圳税务确认", "SZ-TAX-IIT-001"],
        ["印花税", "买卖双方", "个人买卖住房暂免征收", "NAT-TAX-STAMP-001"],
        ["土地增值税", "卖方", "个人销售住房暂免征收", "NAT-TAX-LAT-001"],
      ],
    },
    details: [
      "深圳的满五唯一按广东省范围核验卖方及配偶住房，不能只查深圳市。",
      "2026-01-01 至 2027-12-31，同城卖旧买新且满足条件可申请换购住房个税退税。",
    ],
    note: "合同可以约定买方代付卖方税费，但法定纳税人不会因此改变；退税未到账前不冲减交易现金需求。",
    sources: nationalTaxSources,
    keywords: ["契税", "个税", "增值税", "满五唯一", "计税价"],
  },
  {
    id: "sz-inputs",
    city: "shenzhen",
    category: "必填信息",
    title: "深圳最少需要追问什么",
    summary: "深圳区域差异明显，缺少区或街道时最容易误判资格。",
    details: [
      "房屋所在区；宝安区必须继续确认是否为新安街道。",
      "深户/非深户、连续社保或个税月数、有效深圳经济特区居住证。",
      "家庭在深圳不同政策区域的住房套数。",
      "房屋产权性质、面积、三种价格、卖方持有年限及满五唯一情况。",
      "满五唯一需核验卖方及配偶在广东省的住房；换购退税需补充两笔交易日期、金额、城市和产权人。",
      "公积金需补充缴存身份、连续与累计月数、账户余额、缴存基数、三年提取记录和共同申请人。",
      "贷款方式、实际获批额度和税费承担约定。",
    ],
    keywords: ["宝安", "新安街道", "居住证", "缺失输入", "追问"],
  },
  {
    id: "gz-eligibility",
    city: "guangzhou",
    category: "购房资格",
    title: "广州居民住房限购已取消",
    summary: "自 2024-09-30 起，自然人居民家庭购买广州商品住房，不再按户籍、社保或家庭住房套数限制购买数量。",
    details: [
      "普通商品住房的购房资格一般可返回 eligible。",
      "境外个人不应直接套用居民结论：官方办理问答对工作/学习证明、自用承诺与数量限制存在表述差异，应返回 conditional/needs_review。",
      "企业购房、境外机构、政策性住房资格和非住宅用途不在这条确定性规则内。",
      "家庭住房套数仍然影响契税、商业贷款和公积金认定，不能省略。",
    ],
    note: "GZ-ELIG-001@2024-09-30.1 仅覆盖自然人居民商品住房；GZ-ELIG-FOREIGN-001 对境外个人标记官方来源冲突。",
    sources: [
      {
        title: "广州市政府取消住房限购政策",
        url: "https://www.gz.gov.cn/zwgk/fggw/sfbgtwj/content/post_9896008.html",
      },
      {
        title: "广州不动产登记：境外个人购房问答",
        url: "https://ghzyj.gz.gov.cn/ywpd/bdcdj/bdczswd/content/post_10124570.html",
      },
      {
        title: "增城区住房服务问答：境外个人口径",
        url: "https://www.zc.gov.cn/fw/ztfw/grfw/zffw/content/post_10396347.html",
      },
    ],
    keywords: ["取消限购", "广州户籍", "社保", "住房套数"],
  },
  {
    id: "gz-transfer",
    city: "guangzhou",
    category: "房屋可交易性",
    title: "广州不再审核取得产权证时间",
    summary: "自 2024-05-29 起，居民家庭转让名下住房不再审核取得不动产权证时间。税务上的满二、满五仍需单独判断。",
    details: [
      "继续核验产权证、权利人、共有权、查封、异议登记、抵押权和租赁。",
      "政策性住房的上市条件不能套用普通商品住房规则。",
      "转让不审核持证时间，不代表卖方自动免征增值税或个人所得税。",
    ],
    note: "GZ-TRANSFER-001@2024-05-29.1：转让资格条件和税收持有年限必须分开。",
    sources: [
      {
        title: "广州进一步促进房地产市场平稳健康发展通知",
        url: "https://www.gz.gov.cn/zwgk/fggw/sfbgtwj/content/post_9674048.html",
      },
    ],
    keywords: ["取得产权证", "拿证时间", "满二", "满五", "转让"],
  },
  {
    id: "gz-financing",
    city: "guangzhou",
    category: "贷款与首付",
    title: "广州商业贷款与公积金",
    summary: "广州商贷首套和二套政策最低首付均为 15%；公积金首套和二套均为 20%。",
    table: {
      headers: ["项目", "现行口径", "规则 ID"],
      rows: [
        ["商贷首套最低首付", "15%", "GZ-LOAN-COM-001"],
        ["商贷二套最低首付", "15%", "GZ-LOAN-COM-002"],
        ["公积金首套/二套最低首付", "20% / 20%", "GZ-LOAN-PF-001/002"],
        ["保障性住房最低首付", "15%", "GZ-LOAN-PF-003"],
        ["一人申请最高额度", "80 万元", "GZ-LOAN-PF-004"],
        ["两人及以上最高额度", "160 万元", "GZ-LOAN-PF-005"],
        ["多子女家庭", "最高额度上浮 40%", "GZ-LOAN-PF-006"],
        ["公积金利率", "首套 2.1%/2.6%；二套 2.525%/3.075%", "GZ-LOAN-PF-007"],
        ["基础缴存", "连续足额缴存 6 个月及以上，账户正常", "GZ-LOAN-PF-008"],
        ["第三套", "家庭购买第三套及以上住房不予公积金贷款", "GZ-LOAN-PF-009"],
        ["贷款记录", "有未结清公积金贷款或已使用两次，不予贷款", "GZ-LOAN-PF-010"],
        ["房屋限制", "非住宅、别墅、不能自由上市或存在权利限制等不予贷款", "GZ-LOAN-PF-011"],
        ["交易关系", "部分份额、近亲属及离婚一年内原配偶交易等不予或专项核验", "GZ-LOAN-PF-012"],
        ["申请时序", "二手房完成转移登记后再申请，不予受理", "GZ-LOAN-PF-013"],
      ],
    },
    details: [
      "组合贷款必须同时满足商业贷款和公积金贷款条件。",
      "公积金最高额度必须与缴存、住房套数、使用次数、房屋性质、交易关系和办理时序共同判断。",
      "银行可根据征信、收入、负债、房龄和评估价值提高实际首付或拒绝贷款。",
    ],
    sources: [
      {
        title: "广州商业性住房贷款政策说明",
        url: "https://sw.gz.gov.cn/xxgk/jyta/content/post_10452546.html",
      },
      {
        title: "广州住房公积金贷款政策通知",
        url: "https://www.gz.gov.cn/gfxwj/sbmgfxwj/gzzfgjjglzx/content/post_9994206.html",
      },
      {
        title: "广州公积金贷款服务指南",
        url: "https://gjj.gz.gov.cn/bsfw/qtfw/content/post_5748060.html",
      },
    ],
    keywords: ["首付", "商贷", "公积金", "多子女", "组合贷"],
  },
  {
    id: "gz-tax",
    city: "guangzhou",
    category: "税率税费",
    title: "广州买卖双方税费",
    summary: "广州已取消普通住宅与非普通住宅标准；自然人住房交易仍按家庭套数、面积、持有年限和原值资料计算。",
    table: {
      headers: ["税种", "法定纳税人", "现行判断", "规则 ID"],
      rows: [
        ["契税", "买方", "唯一/二套 ≤140㎡ 为 1%；唯一 >140㎡ 为 1.5%；二套 >140㎡ 为 2%；其他一般 3%", "GZ-TAX-DEED-001"],
        ["增值税", "卖方", "不足 2 年按 3% 征收率；满 2 年免征", "GZ-TAX-VAT-001"],
        ["个人所得税", "卖方", "所得额 ×20%；满五唯一免征；核定口径由广州税务确认", "GZ-TAX-IIT-001"],
        ["印花税", "买卖双方", "个人买卖住房暂免征收", "NAT-TAX-STAMP-001"],
        ["土地增值税", "卖方", "个人销售住房暂免征收", "NAT-TAX-LAT-001"],
      ],
    },
    details: [
      "广州的满五唯一按广东省范围核验卖方及配偶住房，不能只查广州市。",
      "2026-01-01 至 2027-12-31，同城卖旧买新且满足条件可申请换购住房个税退税。",
      "广州税务表列明附加税费计算口径；只有实际产生增值税时才计算相应附加。",
    ],
    sources: [
      ...nationalTaxSources,
      {
        title: "广州税务 2026 年涉税不动产交易适用税费表",
        url: "https://guangdong.chinatax.gov.cn/gdsw/gzsw_xzfw/2026-04/20/content_a232b5691511474898f7b15f1cd36485.shtml",
      },
    ],
    keywords: ["普通住宅", "非普通住宅", "契税", "满二", "满五唯一"],
  },
  {
    id: "gz-inputs",
    city: "guangzhou",
    category: "必填信息",
    title: "广州最少需要追问什么",
    summary: "广州无需为限购追问户籍和社保，但税费、贷款和房屋转让仍需要完整事实。",
    details: [
      "买方是否为境外个人；如是，需补充境内工作/学习、自用自住及登记、外汇材料。",
      "家庭住房套数、房屋产权性质和建筑面积。",
      "合同价、税务计税价格和银行评估价。",
      "卖方取得日期、是否满二、是否满五唯一、原值和扣除凭证。",
      "满五唯一需核验卖方及配偶在广东省的住房；换购退税需补充两笔交易日期、金额、城市和产权人。",
      "公积金需补充缴存月数、既往使用次数、未结清贷款、房屋限制、交易关系和登记时序。",
      "贷款方式、银行实际批准额度、中介报价和税费承担约定。",
    ],
    keywords: ["缺失输入", "追问", "户籍", "社保", "住房套数"],
  },
  {
    id: "sh-eligibility",
    city: "shanghai",
    category: "购房资格与结构",
    title: "上海按外环内外判断购房资格",
    summary: "上海不能套用不限购城市模板。先判断外环内外，再结合沪籍、居住证年限、连续社保/个税年限和分区住房套数。",
    table: {
      headers: ["家庭类型", "外环内", "外环外", "规则 ID"],
      rows: [
        ["沪籍家庭或成年单身", "最多 2 套", "不限套数", "SH-ELIG-001"],
        ["非沪籍，连续社保/个税满 1 年不足 3 年", "最多 1 套", "不限套数", "SH-ELIG-002"],
        ["非沪籍，连续社保/个税满 3 年", "最多 2 套", "不限套数", "SH-ELIG-003"],
        ["非沪籍，上海居住证满 5 年", "全市最多 1 套且不要求社保/个税", "同左", "SH-ELIG-004"],
      ],
    },
    note: "知识形态：restricted_spatial_quota + local_property_tax。特殊人才、境外个人和企业购房转人工核验。",
    sources: shanghaiSources,
    keywords: ["上海", "外环", "沪籍", "非沪籍", "居住证五年", "限购"],
  },
  {
    id: "sh-financing",
    city: "shanghai",
    category: "贷款与首付",
    title: "上海二套首付存在差异化区域",
    summary: "首套商贷最低 15%；二套一般 25%，临港及嘉定、青浦、松江、奉贤、宝山、金山为 20%。公积金也采用一般区与差异化区域分流。",
    table: {
      headers: ["方案", "首套", "二套", "规则 ID"],
      rows: [
        ["商业贷款", "15%", "一般 25%；差异化区域 20%", "SH-LOAN-COM-001"],
        ["公积金贷款", "20%", "一般 25%；差异化区域 20%", "SH-LOAN-PF-001"],
        ["公积金最高额度", "个人/家庭 100/200 万；含补充 120/240 万", "个人/家庭 80/160 万；含补充 100/200 万", "SH-LOAN-PF-002"],
      ],
    },
    details: ["行政区是贷款输入，不只是购房资格输入。", "最低首付不等于银行对具体借款人和房源的最终批贷。"],
    sources: shanghaiSources,
    keywords: ["上海首付", "临港", "嘉定", "宝山", "补充公积金"],
  },
  {
    id: "sh-tax-special",
    city: "shanghai",
    category: "税费与本地特殊项",
    title: "上海房产税与过户税必须分开",
    summary: "契税、增值税和满五唯一个税先按全国规则；上海个人住房房产税属于持有环节，应单独返回状态和年度金额。",
    details: [
      "上海已取消普通/非普通住房标准；不能核实原值时，个人转让住房个税可按转让收入 1% 核定。",
      "满五唯一按上海市范围核验卖方及配偶住房。",
      "房产税需补购房日期、房屋类型、家庭人数、家庭面积和免税资格；信息不足时返回 unknown，不得报 0 元。",
    ],
    note: "规则 SH-TAX-PROPERTY-ROUTE-001：持有税不能直接并入过户时现金总额。",
    sources: [...shanghaiSources, ...nationalTaxSources],
    keywords: ["上海房产税", "普通住房标准", "核定个税1%", "满五唯一"],
  },
  {
    id: "tj-eligibility",
    city: "tianjin",
    category: "购房资格与结构",
    title: "天津不限购，但贷款套数按目标区认定",
    summary: "自 2024-10-16 起，本市和非本市居民购买普通新房、二手房不再提交社保或个税资格材料；贷款仍需输入拟购住房所在区的套数。",
    table: {
      headers: ["判断层", "现行结论", "规则 ID"],
      rows: [
        ["普通商品住房购房资格", "全市开放，不因非津户籍或社保年限不合格", "TJ-ELIG-001"],
        ["商业贷款套数", "按拟购住房所在行政区认定", "TJ-LOAN-COM-001"],
        ["特殊产权", "直管公产使用权等转专项规则", "TJ-TRANSFER-001"],
      ],
    },
    sources: tianjinSources,
    keywords: ["天津不限购", "按区认定", "非津户籍", "直管公产"],
  },
  {
    id: "tj-financing",
    city: "tianjin",
    category: "贷款与首付",
    title: "天津商贷 15%，公积金 20%",
    summary: "商贷首套、二套政策最低首付均为 15%；公积金首套、二套均为 20%，但实际额度受房龄、缴存、征信和评估价约束。",
    table: {
      headers: ["项目", "现行口径", "规则 ID"],
      rows: [
        ["商贷首套/二套", "最低首付 15% / 15%", "TJ-LOAN-COM-001"],
        ["公积金首套/二套", "最低首付 20% / 20%", "TJ-LOAN-PF-001"],
        ["公积金最高额度", "首套 120 万；二套 100 万", "TJ-LOAN-PF-002"],
        ["多子女家庭", "首套 144 万；二套 120 万", "TJ-LOAN-PF-003"],
        ["二手房最长期限", "30 年", "TJ-LOAN-PF-004"],
      ],
    },
    note: "只给天津全市住房套数、未给目标区套数时，商贷认定返回 conditional。",
    sources: tianjinSources,
    keywords: ["天津首付", "120万", "多子女", "二手房30年"],
  },
  {
    id: "tj-transfer-tax-inputs",
    city: "tianjin",
    category: "特殊产权与税费",
    title: "直管公产使用权不是普通商品房产权",
    summary: "取消商品住房限购不等于所有房屋使用权都可自由取得。直管公产、公有住房承租权、限价房和保障房必须先识别权利类型。",
    details: [
      "普通住房税费执行全国规则，满五唯一按天津市范围核验。",
      "最少追问：目标区、该区家庭套数、产权证记载、面积和三种价格、卖方取得日期、贷款方式与费用承担。",
      "直管公产使用权的价款、税费和登记路径不能复用普通所有权买卖公式。",
    ],
    sources: [...tianjinSources, ...nationalTaxSources],
    keywords: ["天津直管公产", "公有住房", "使用权", "天津税费"],
  },
  {
    id: "wh-eligibility",
    city: "wuhan",
    category: "购房资格与结构",
    title: "武汉普通商品住房不再审核个人购房资格",
    summary: "武汉已取消普通商品住房个人购房资格审查，不再按户籍、社保或已有套数限制普通二手房购买资格。",
    details: [
      "WH-ELIG-001：自然人购买普通二手商品住房为 eligible；企业、境外个人和政策性住房例外。",
      "取消购房资格审查不免除产权、查封、抵押、共有、租赁和居住权核验。",
      "已届满的阶段性购房补贴不得进入当前现金总额。",
    ],
    sources: wuhanSources,
    keywords: ["武汉不限购", "购房资格", "补贴有效期"],
  },
  {
    id: "wh-financing",
    city: "wuhan",
    category: "贷款与首付",
    title: "武汉公积金二手房按三价取低",
    summary: "公积金首套/二套最高贷款成数为 80%/70%；二手房价值基数取评估价、成交价和计税价格中的最低值。",
    table: {
      headers: ["项目", "现行口径", "规则 ID"],
      rows: [
        ["商贷", "全国 15% 政策底线，银行个案确认", "WH-LOAN-COM-001"],
        ["公积金首套", "最高成数 80%，最低首付 20%", "WH-LOAN-PF-001"],
        ["公积金二套", "最高成数 70%，最低首付 30%", "WH-LOAN-PF-002"],
        ["最高额度", "单缴存人 120 万；双缴存人 150 万", "WH-LOAN-PF-003"],
        ["二手房价值基数", "min(评估价, 成交价, 计税价)", "WH-LOAN-PF-BASE-001"],
      ],
    },
    sources: wuhanSources,
    keywords: ["武汉公积金", "三价取低", "120万", "150万", "首付30%"],
  },
  {
    id: "wh-tax-inputs",
    city: "wuhan",
    category: "税费与必填信息",
    title: "武汉缺三价时不能精确计算公积金首付",
    summary: "税费执行全国规则，满五唯一按湖北省范围核验；贷款计算还需同时取得成交价、评估价和计税价格。",
    details: [
      "最少追问产权性质、面积、三种价格、卖方取得日期和湖北省家庭住房情况。",
      "补充贷款方式、公积金缴存人数和记录、房龄、收入征信、费用承担。",
      "商贷只确认全国 15% 底线时，应写银行核验，不输出保证比例。",
    ],
    sources: [...wuhanSources, ...nationalTaxSources],
    keywords: ["湖北满五唯一", "武汉计税价", "银行核验", "缺失输入"],
  },
  {
    id: "hz-eligibility-points",
    city: "hangzhou",
    category: "购房资格与积分消歧",
    title: "杭州不限购，居住证积分不是买房门槛",
    summary: "2024-05-09 起杭州全面取消住房限购。购房产生的居住证积分用于落户相邻场景，不决定普通二手房能否购买或房源排序。",
    table: {
      headers: ["问题", "现行结论", "规则 ID"],
      rows: [
        ["普通商品住房资格", "不审查户籍、社保和购买套数", "HZ-ELIG-001"],
        ["购房并实际居住", "现行居住证积分可计 80 分", "HZ-POINTS-001"],
        ["二手房用于积分", "原户口需迁出，且一年内未被用于积分落户", "HZ-POINTS-001"],
      ],
    },
    note: "用户问“杭州买房要多少积分”时，先确认是在问购房、落户、学位还是保障房。",
    sources: hangzhouSources,
    keywords: ["杭州积分", "落户80分", "不限购", "原户口迁出"],
  },
  {
    id: "hz-financing",
    city: "hangzhou",
    category: "贷款与首付",
    title: "杭州商贷首套认定需要目标区与挂牌状态",
    summary: "拟购区无房，或仅有一套且正在挂牌出售，可按现行商贷首套路径认定；公积金首套、二套最低首付均为 20%。",
    table: {
      headers: ["项目", "现行口径", "规则 ID"],
      rows: [
        ["商贷首套认定", "拟购区无房，或仅一套且挂牌出售", "HZ-LOAN-COM-001"],
        ["商贷首付", "全国 15% 政策底线，银行个案确认", "HZ-LOAN-COM-002"],
        ["公积金首套/二套", "最低首付均为 20%", "HZ-LOAN-PF-001"],
        ["公积金最高额度", "个人 65 万；家庭 130 万", "HZ-LOAN-PF-002"],
      ],
    },
    sources: hangzhouSources,
    keywords: ["杭州首套", "挂牌出售", "65万", "130万", "公积金20%"],
  },
  {
    id: "hz-tax-inputs",
    city: "hangzhou",
    category: "税费与必填信息",
    title: "购房资格开放后，税贷套数仍要分别判断",
    summary: "杭州普通二手房税费执行全国规则，满五唯一按浙江省范围核验；不限购不能代替契税、商贷或公积金套数认定。",
    details: [
      "最少追问目标区、该区住房与挂牌状态、产权性质、面积和三种价格。",
      "补充卖方取得日期、卖方及配偶在浙江省住房、贷款方式与公积金缴存。",
      "若另问积分落户，再补实际居住、原户口迁出和一年内积分使用事实。",
    ],
    sources: [...hangzhouSources, ...nationalTaxSources],
    keywords: ["浙江满五唯一", "杭州契税", "套数认定", "必填信息"],
  },
  {
    id: "su-eligibility-transfer",
    city: "suzhou",
    category: "购房与转让",
    title: "苏州普通住房不限购不限售，特殊房源除外",
    summary: "苏州已逐步取消普通商品住房购房和一般限售。定向销售、保障性或合同另有限制的房屋仍需读取原始项目文件。",
    table: {
      headers: ["判断", "现行结论", "规则 ID"],
      rows: [
        ["普通商品住房资格", "不再按原户籍、社保和套数限购", "SU-ELIG-001"],
        ["普通商品住房一般限售", "已取消", "SU-TRANSFER-001"],
        ["定向/保障/合同限制", "专项核验，返回 conditional", "SU-TRANSFER-001"],
      ],
    },
    note: "苏州下辖县级市办理口径可能不同，必须输入具体区或县级市。",
    sources: suzhouSources,
    keywords: ["苏州不限购", "苏州不限售", "县级市", "定向住房"],
  },
  {
    id: "su-financing",
    city: "suzhou",
    category: "贷款与时效",
    title: "苏州公积金 15% 首付是限时规则",
    summary: "2025-09-01 起两年内，公积金首套、二套最低首付均为 15%；2026-06-01 起个人/家庭最高额度为 150/200 万元。",
    table: {
      headers: ["项目", "现行口径", "有效期/规则 ID"],
      rows: [
        ["商贷", "最低首付 15%，银行确认", "SU-LOAN-COM-001"],
        ["公积金首套/二套", "最低首付均为 15%", "2025-09-01—2027-08-31 / SU-LOAN-PF-001"],
        ["公积金额度", "个人 150 万；家庭 200 万", "2026-06-01 起 / SU-LOAN-PF-002"],
        ["首套认定", "全国无未结清公积金贷款可按首套政策", "SU-LOAN-PF-003"],
      ],
    },
    note: "2027-09-01 后若没有续期或替代文件，15% 规则返回 unknown/needs_review，不能沿用。",
    sources: suzhouSources,
    keywords: ["苏州15%", "2027年8月31日", "150万", "200万", "规则失效"],
  },
  {
    id: "su-tax-inputs",
    city: "suzhou",
    category: "税费与必填信息",
    title: "苏州需要输入具体区或县级市",
    summary: "税费执行全国规则，满五唯一按江苏省范围核验；县级市流程差异和阶段性公积金规则都要求保留查询日期。",
    details: [
      "追问具体区/县级市、房屋是否定向或保障属性、产权负担、面积和三种价格。",
      "补充卖方取得日期及江苏省家庭住房、贷款方式、公积金缴存与贷款记录。",
      "旧页面显示 20% 与新正式通知冲突时，优先使用较新正式通知并展示有效期。",
    ],
    sources: [...suzhouSources, ...nationalTaxSources],
    keywords: ["江苏满五唯一", "苏州县级市", "旧页面20%", "政策版本"],
  },
  {
    id: "cd-eligibility-transfer",
    city: "chengdu",
    category: "购房与转让",
    title: "成都不限购，取得证后可上市",
    summary: "2024-04-29 起全市不再审核购房资格；2024-10-15 起普通住房取得不动产权证后即可上市，但权利负担和特殊项目限制仍需核验。",
    table: {
      headers: ["判断", "现行结论", "规则 ID"],
      rows: [
        ["普通商品住房资格", "不审查户籍、社保和套数", "CD-ELIG-001"],
        ["普通二手房一般限售", "取得产权证后可上市", "CD-TRANSFER-001"],
        ["满二/满五", "仍是税收年限，不是转让限制", "CD-SCOPE-001"],
      ],
    },
    sources: chengduSources,
    keywords: ["成都不限购", "取得证后上市", "满二", "限售取消"],
  },
  {
    id: "cd-financing",
    city: "chengdu",
    category: "贷款与时效",
    title: "成都 2026 年公积金政策年底到期",
    summary: "2026-03-25 至 2026-12-31，单缴存人/双缴存人最高 80/120 万元；无未结清公积金贷款可按首套，最低首付 20%。",
    table: {
      headers: ["项目", "现行口径", "规则 ID"],
      rows: [
        ["商贷", "全国 15% 政策底线，银行确认", "CD-LOAN-COM-001"],
        ["公积金首套", "无未结清公积金贷款，最低首付 20%", "CD-LOAN-PF-001"],
        ["公积金额度", "单缴存人 80 万；双缴存人 120 万", "CD-LOAN-PF-002"],
        ["特殊家庭上浮", "符合现行条件可上浮 20%", "CD-LOAN-PF-003"],
      ],
    },
    note: "以上公积金子规则 effective_to = 2027-01-01；之后无续期证据时必须 needs_review。",
    sources: chengduSources,
    keywords: ["成都公积金", "80万", "120万", "2026年12月31日", "阶段性"],
  },
  {
    id: "cd-tax-inputs",
    city: "chengdu",
    category: "税费与必填信息",
    title: "取消限售不能替代满二满五判断",
    summary: "成都税费执行全国规则，满五唯一按四川省范围核验；能上市不代表卖方自动免增值税或个税。",
    details: [
      "追问查询日期、产权性质、取得证日期、面积、三种价格和费用承担。",
      "补充卖方税务取得日期与四川省家庭住房、公积金贷款状态、缴存人数。",
      "政策性住房和定向项目不能只凭取得产权证判定自由转让。",
    ],
    sources: [...chengduSources, ...nationalTaxSources],
    keywords: ["四川满五唯一", "成都增值税", "能卖不等于免税", "查询日期"],
  },
  {
    id: "cq-eligibility-structure",
    city: "chongqing",
    category: "购房资格与结构",
    title: "重庆不限购，但贷款和房产税都要看区位",
    summary: "普通自然人商品住房没有一般性户籍、社保或套数限购；贷款套数按拟购区判断，主城试点区域的高档住房和独栋住宅另查房产税。",
    table: {
      headers: ["判断层", "现行结论", "规则 ID"],
      rows: [
        ["普通商品住房资格", "不作一般限购审查", "CQ-ELIG-001"],
        ["贷款住房套数", "按拟购住房所在区认定", "CQ-LOAN-PF-001"],
        ["本地持有税", "试点区高档/独栋住房独立判断", "CQ-TAX-PROPERTY-001"],
      ],
    },
    note: "只回答“重庆不限购”会遗漏贷款地域和个人住房房产税两条关键分支。",
    sources: chongqingSources,
    keywords: ["重庆不限购", "按区认定", "主城九区", "房产税试点"],
  },
  {
    id: "cq-financing",
    city: "chongqing",
    category: "贷款与首付",
    title: "重庆公积金首套二套最高成数均为 80%",
    summary: "公积金个人/夫妻参贷最高 80/120 万元，多子女家庭 100/160 万元；二手房价值基数取评估价与登记成交价较低值。",
    table: {
      headers: ["项目", "现行口径", "规则 ID"],
      rows: [
        ["商贷", "全国 15% 政策底线，银行确认", "CQ-LOAN-COM-001"],
        ["公积金首套/二套", "最高成数均 80%，最低首付 20%", "CQ-LOAN-PF-001"],
        ["普通家庭额度", "个人 80 万；夫妻参贷 120 万", "CQ-LOAN-PF-002"],
        ["多子女家庭额度", "个人 100 万；夫妻参贷 160 万", "CQ-LOAN-PF-003"],
        ["二手房价值基数", "min(评估价, 登记成交价)", "CQ-LOAN-PF-004"],
      ],
    },
    details: ["两次及以上公积金贷款记录，或拟购区三套及以上住房等情形，不得只凭首付比例判定可贷。"],
    sources: chongqingSources,
    keywords: ["重庆公积金", "80万", "160万", "评估价", "区内套数"],
  },
  {
    id: "cq-property-tax",
    city: "chongqing",
    category: "个人住房房产税",
    title: "重庆试点房产税需单独计算年度持有成本",
    summary: "试点区域内独栋商品住宅和新购高档住房需判断房产税。普通过户税与持有税分别返回，缺房屋类型或区域时不能报 0 元。",
    formula: ["年应纳税额 =（应税住房交易价 × 70% − 可扣除免税面积对应计税价值）× 0.5%"],
    details: [
      "家庭一套应税住房可适用 180㎡免税面积，具体分摊和申报以税务口径为准。",
      "2025-01-01 起，无重庆户籍、企业或工作的人员购买普通住房不再因此单独纳税；高档和独栋仍需判断。",
      "满五唯一按重庆市范围核验；过户税继续使用全国规则。",
    ],
    sources: [...chongqingSources, ...nationalTaxSources],
    keywords: ["重庆房产税", "70%", "0.5%", "180平方米", "独栋", "高档住房"],
  },
  {
    id: "xa-eligibility-structure",
    city: "xian",
    category: "购房资格与结构",
    title: "西安不限购，公积金必须先选择管理中心",
    summary: "居民购买普通新房、二手房不再审核购房资格；公积金知识采用双管理中心结构，西安中心与陕西省中心不得混算。",
    table: {
      headers: ["判断", "现行结论", "规则 ID"],
      rows: [
        ["普通商品住房资格", "不按户籍、社保和已有套数限购", "XA-ELIG-001"],
        ["公积金路由", "先输入 fund_administration_center", "XA-LOAN-PF-ROUTE-001"],
        ["中心未知", "额度与资格返回 conditional", "XA-LOAN-PF-ROUTE-001"],
      ],
    },
    note: "购房资格取消的公开依据目前以授权公开报道快照为补充来源，市级原文仍列入监测补强项。",
    sources: xianSources,
    keywords: ["西安不限购", "陕西省中心", "西安中心", "fund_administration_center"],
  },
  {
    id: "xa-financing",
    city: "xian",
    category: "贷款与首付",
    title: "省中心额度不能当成西安中心额度",
    summary: "已核验的陕西省中心口径为首套/再次使用公积金最低首付 20%/25%，单人/双人最高 75/100 万元；西安中心需使用其自身现行规则。",
    table: {
      headers: ["管理中心", "首付与额度", "规则 ID"],
      rows: [
        ["陕西省住房资金管理中心", "首套 20%、再次 25%；单人 75 万、双人 100 万", "XA-LOAN-PF-SX-001"],
        ["西安住房公积金管理中心", "按中心当前正式规则核验，不能套省中心数字", "XA-LOAN-PF-XA-001"],
        ["商业贷款", "全国 15% 政策底线，银行个案确认", "XA-LOAN-COM-001"],
      ],
    },
    details: ["省中心二手房房龄一般不超过 30 年，房龄与贷款期限之和不超过 40 年。"],
    sources: xianSources,
    keywords: ["西安公积金", "省中心", "75万", "100万", "房龄30年"],
  },
  {
    id: "xa-tax-inputs",
    city: "xian",
    category: "税费与必填信息",
    title: "西安公积金缺管理中心时不能给确定额度",
    summary: "税费执行全国规则，满五唯一按陕西省范围核验；贷款追问必须包含缴存管理中心、房龄、缴存人数和贷款记录。",
    details: [
      "追问产权性质、面积、合同价、评估价和计税价。",
      "补充卖方取得日期、卖方及配偶在陕西省住房、费用承担约定。",
      "中心未知时只提供分流提示，不选择对用户更有利的一套数字。",
    ],
    sources: [...xianSources, ...nationalTaxSources],
    keywords: ["陕西满五唯一", "西安必填信息", "管理中心未知", "公积金额度"],
  },
  {
    id: "nj-eligibility-transfer",
    city: "nanjing",
    category: "购房与转让",
    title: "南京普通商品住房不限购不限售",
    summary: "普通商品住房不再要求原购房证明，一般限售也已取消；取得不动产权证并排除权利障碍后可上市。",
    table: {
      headers: ["判断", "现行结论", "规则 ID"],
      rows: [
        ["普通商品住房资格", "不再要求原购房证明", "NJ-ELIG-001"],
        ["普通商品住房一般限售", "取得不动产权证后可上市", "NJ-TRANSFER-001"],
        ["配售型保障房", "专门平台和买方资格，不按普通房自由出售", "NJ-TRANSFER-AFFORDABLE-001"],
      ],
    },
    sources: nanjingSources,
    keywords: ["南京不限购", "南京不限售", "购房证明", "配售型保障房"],
  },
  {
    id: "nj-financing",
    city: "nanjing",
    category: "贷款与首付",
    title: "南京公积金首套二套均为 20% 首付",
    summary: "公积金个人/家庭最高额度为 80/100 万元；2026 年扩展父母与子女共同借款路径，但共同借款不代表无条件提高额度。",
    table: {
      headers: ["项目", "现行口径", "规则 ID"],
      rows: [
        ["商贷", "全国 15% 政策底线，银行确认", "NJ-LOAN-COM-001"],
        ["公积金首套/二套", "最低首付均为 20%", "NJ-LOAN-PF-001"],
        ["公积金额度", "个人 80 万；家庭 100 万", "NJ-LOAN-PF-002"],
        ["父母子女共同借款", "满足中心条件可走扩展路径", "NJ-LOAN-PF-003"],
      ],
    },
    sources: nanjingSources,
    keywords: ["南京公积金", "80万", "100万", "共同借款", "父母子女"],
  },
  {
    id: "nj-special-tax-inputs",
    city: "nanjing",
    category: "特殊住房与税费",
    title: "配售型保障房满五年也不是普通二手房",
    summary: "配售型保障房达到规定年限后仍可能只能经指定平台转让给符合条件的买方；必须读取原购房合同和项目类型。",
    details: [
      "普通住房税费执行全国规则，满五唯一按江苏省范围核验。",
      "追问房屋是否保障/共有产权/定向住房、取得证日期、权利负担、面积和三种价格。",
      "补充卖方取得日期及江苏省住房、公积金共同借款人与缴存信息、费用承担。",
    ],
    sources: [...nanjingSources, ...nationalTaxSources],
    keywords: ["南京保障房", "满五年", "指定平台", "江苏满五唯一"],
  },
  {
    id: "common-priority",
    city: "common",
    category: "知识范围",
    title: "全国通则如何与城市政策一起使用",
    summary: "所有城市先读取全国法律和政策底线，再叠加省、市、区及特殊房屋规则；最后以税务、登记、公积金中心和贷款银行对本案的正式审核为准。",
    table: {
      headers: ["层级", "负责回答", "不能替代"],
      rows: [
        ["全国通则", "产权登记、禁止转让、共有/抵押/租赁、定金、信贷底线、全国税收", "城市限购、网签和特殊住房细则"],
        ["城市/区域规则", "资格地域、城市首付、公积金、办事路径", "银行授信和个案登记结果"],
        ["机构个案审核", "计税价格、贷款额度、登记受理、实际收费", "知识库中的一般规则"],
      ],
    },
    details: [
      "未指定城市时，全国知识只能回答真正通用的部分；购房资格应返回 unknown 并追问城市、区域和房屋性质。",
      "全国知识包版本为 cn-tax@2026-07-16.1；12 个城市分别保留自己的政策包版本和知识形态。",
      "全国知识包是 2026-07-16 的已审核快照，各条规则仍按自身生效日期查询，不能把快照日期当作所有法律的生效日。",
    ],
    note: "优先级：国家法律和全国政策底线 → 城市现行规则 → 机构对本案的正式审核。",
    sources: [...nationalPropertySources, ...nationalFinanceSources, ...nationalTaxSources],
    keywords: ["全国通则", "城市覆盖", "优先级", "全国知识包", "cn-tax@2026-07-16.1"],
  },
  {
    id: "common-title-transfer",
    city: "common",
    category: "产权与过户",
    title: "签合同不等于已经取得房屋产权",
    summary: "买卖合同依法成立、完成网签、支付房款和产权转移是不同状态。房屋所有权转移以记载于不动产登记簿为准。",
    table: {
      headers: ["判断项", "全国规则", "规则 ID"],
      rows: [
        ["合同状态", "合同通常自依法成立时生效；未登记不当然导致合同无效", "NAT-REG-001"],
        ["产权状态", "依法应登记的房屋所有权转让，自登记时发生效力", "NAT-REG-001"],
        ["禁止转让", "查封/限制、收回土地、共有未书面同意、权属争议、无证等不得直接转让", "NAT-TRANSFER-001"],
        ["登记资料", "权利人、利害关系人依法申请查询复制，实际材料和授权按当地流程", "NAT-REG-001"],
      ],
    },
    details: [
      "查封、权属争议或共有未同意等障碍有可能解除；回答应同时写当前状态和解除后重新核验的条件。",
      "网签、资金监管和转移登记的先后顺序由城市流程决定，全国层不虚构窗口顺序。",
      "农村宅基地、小产权房、集体土地住房和特殊政策住房不能只套普通商品住房规则。",
    ],
    sources: nationalPropertySources.slice(0, 2),
    keywords: ["产权", "过户", "登记簿", "合同生效", "查封", "权属争议", "共有同意", "NAT-REG-001"],
  },
  {
    id: "common-rights-risk",
    city: "common",
    category: "权利负担",
    title: "抵押、租赁、共有和居住权必须单独核验",
    summary: "这些权利不一定让交易永久无法进行，但会改变能否过户、何时交房和买方能否立即占有使用，不能凭卖方口头承诺跳过。",
    table: {
      headers: ["主题", "全国规则", "缺信息时"],
      rows: [
        ["共有", "核验共有类型、份额和其他共有人书面同意", "conditional；明确拒绝则当前 ineligible"],
        ["抵押", "抵押期间可依法转让，另有约定从其约定；应通知抵押权人，抵押不自动消灭", "conditional"],
        ["租赁", "所有权变化不影响有效租赁合同，即买卖不破租赁", "conditional"],
        ["承租人优先购买", "通常需通知承租人并核验同等条件及法定例外", "conditional"],
        ["登记居住权", "可能持续影响占有和使用；核验期限与消灭条件", "conditional"],
      ],
    },
    note: "有抵押不等于法律上一律不能卖；房屋卖出也不等于租约自动终止。规则：NAT-COOWN-001、NAT-MORTGAGE-001、NAT-LEASE-001、NAT-TENANT-PRIORITY-001、NAT-RESIDENCE-001。",
    sources: nationalPropertySources.slice(0, 2),
    keywords: ["抵押", "带押过户", "租赁", "买卖不破租赁", "优先购买权", "居住权", "共有人"],
  },
  {
    id: "common-contract-deposit",
    city: "common",
    category: "合同与定金",
    title: "定金上限、订金消歧与合同风险",
    summary: "法律意义上的定金不得超过主合同标的额 20%。是否没收或双倍返还，要看真实约定、实际交付、违约方和合同目的是否不能实现。",
    table: {
      headers: ["问题", "全国规则", "规则 ID"],
      rows: [
        ["定金上限", "不超过主合同标的额 20%；超过部分不产生定金效力", "NAT-DEPOSIT-001"],
        ["给付方违约", "符合定金罚则条件时无权请求返还", "NAT-DEPOSIT-001"],
        ["收受方违约", "符合定金罚则条件时双倍返还", "NAT-DEPOSIT-001"],
        ["违约金 + 定金", "通常由守约方选择一种适用，不直接自动叠加", "NAT-DEPOSIT-001"],
        ["订金/意向金", "名称不决定性质，读取合同文字和付款凭证", "NAT-DEPOSIT-001"],
      ],
    },
    details: [
      "合同还应写清贷款未获批、抵押处理、过户障碍、租客腾退、户口迁出、交房和欠费结清。",
      "代理签约必须核验授权书、授权范围、期限和原件；不能只看聊天截图或口头转述。",
    ],
    sources: nationalPropertySources.slice(0, 1),
    keywords: ["定金", "订金", "意向金", "20%", "双倍返还", "违约金", "授权委托"],
  },
  {
    id: "common-national-financing",
    city: "common",
    category: "全国信贷底线",
    title: "15% 是全国底线，不是实际首付承诺",
    summary: "全国层面商业性个人住房贷款最低首付比例不低于 15%；城市可以提高或细分，银行还会按借款人和房屋风险决定实际贷款额。",
    table: {
      headers: ["项目", "全国口径", "规则版本"],
      rows: [
        ["商贷最低首付", "全国层面不低于 15%；城市/区域可提高或细分", "NAT-LOAN-COM-FLOOR-001@2024-09-24.1"],
        ["商贷利率", "取消全国层面首套、二套利率政策下限；实际仍由城市机制和银行定价", "NAT-LOAN-COM-RATE-001@2024-05-17.1"],
        ["公积金首套利率", "≤5 年 2.10%；>5 年 2.60%", "NAT-LOAN-PF-RATE-001@2025-05-08.1"],
        ["公积金二套利率", "≤5 年不低于 2.525%；>5 年不低于 3.075%", "NAT-LOAN-PF-RATE-001@2025-05-08.1"],
      ],
    },
    details: [
      "执行顺序：全国底线 → 城市现行比例 → 银行评估与风险审批 → 实际获批贷款和首付。",
      "北京、深圳二套现行商贷最低首付 20%，高于全国 15% 底线；广州当前城市规则统一为 15%。",
      "公积金利率不等于公积金申请资格、首付或可贷额度，后者必须读取当地中心规则。",
    ],
    sources: nationalFinanceSources,
    keywords: ["全国首付", "15%", "房贷利率下限", "公积金利率", "银行审批", "NAT-LOAN-COM-FLOOR-001"],
  },
  {
    id: "common-services-fees",
    city: "common",
    category: "费用与资金安全",
    title: "登记费、经纪费和交易资金监管",
    summary: "住宅不动产登记费有国家收费标准，经纪费没有全国固定百分比；房款应优先通过所在地交易资金监管安排支付。",
    table: {
      headers: ["项目", "全国规则", "回答方式"],
      rows: [
        ["住宅不动产登记费", "住宅及建设用地使用权一体登记，国家标准 80 元/件", "核验事项、减免和当地实收后计入"],
        ["经纪基本服务", "房源客源、带看、合同、协助登记等必要服务", "与延伸服务分别列价"],
        ["经纪延伸服务", "贷款代办等额外服务可单独提供", "不得捆绑收费"],
        ["经纪收费", "交易各方协商，无全国统一费率", "读取收费清单和实际报价"],
        ["资金监管", "国家意见要求加强存量房交易资金监管", "读取当地账户、节点和例外"],
      ],
    },
    note: "80 元是按件的国家标准，不是买卖双方各 80 元；免收、减收和第二本证书等情形需按实际登记事项核验。规则：NAT-FEE-REG-001、NAT-BROKER-001、NAT-FUND-SUPERVISION-001。",
    sources: nationalPropertySources.slice(2),
    keywords: ["登记费", "80元", "中介费", "经纪费", "延伸服务", "资金监管", "监管账户"],
  },
  {
    id: "common-process",
    city: "common",
    category: "交易流程",
    title: "全国通用的九步核验清单",
    summary: "全国层提供完整的风险核验顺序，但网签、资金监管、带押过户和组合贷的窗口顺序仍由城市规则决定。",
    details: [
      "1. 核验买卖双方身份、婚姻/共有关系和代理权限。",
      "2. 查询登记簿、产权证、查封/抵押/租赁/居住权和特殊房屋性质。",
      "3. 分别核验城市购房资格、契税住房套数、商贷和公积金套数。",
      "4. 完成贷款预审、房屋评估和现金缺口确认。",
      "5. 约定合同、定金、贷款失败、税费承担、违约和腾退事项。",
      "6. 办理当地网签备案并使用交易资金监管。",
      "7. 完成税费申报、贷款审批和抵押处理。",
      "8. 办理转移登记及新抵押登记。",
      "9. 完成交房、钥匙、物业水电、户口、维修资金和欠费结算。",
    ],
    note: "流程不是计算器步骤，而是 Agent 回答“还缺什么、下一步核验什么”的全国知识清单。",
    sources: nationalPropertySources,
    keywords: ["交易流程", "网签", "资金监管", "过户", "交房", "户口迁出", "物业欠费"],
  },
  {
    id: "common-boundaries",
    city: "common",
    category: "口径边界",
    title: "AI 回答前必须先消歧",
    summary: "“首套”“满二”“满五唯一”“不限购”“最高额度”和“积分”都不是单义词；场景未确认时不能直接套规则。",
    table: {
      headers: ["用户说法", "必须拆分的口径", "错误回答风险"],
      rows: [
        ["首套/二套", "购房资格套数、契税家庭套数、商贷认定、公积金认定", "把一种认定替代另三种"],
        ["满二/满五", "税务取得时间、满五唯一的家庭与省级范围", "把满二当可交易性或只查卖方本人"],
        ["不限购", "只代表普通居民商品住房购买数量限制的变化", "误称贷款、税费、产权限制也取消"],
        ["最高可贷", "政策封顶、余额倍数、还款能力、房屋限制、银行授信", "把封顶金额当实际批贷"],
        ["深圳积分", "普通二手房、新房意向登记、保障房、入户、学位", "给普通二手房虚构统一积分门槛"],
        ["杭州积分", "普通二手房购房资格、居住证积分落户、学位", "把落户 80 分误成买房门槛"],
      ],
    },
    note: "普通深圳二手商品住房没有统一积分排名；杭州居住证购房积分不决定普通二手房资格；广州境外个人来源冲突时返回 conditional/needs_review。",
    keywords: ["消歧", "首套", "满五唯一", "不限购", "深圳积分", "杭州积分", "最高额度", "境外个人"],
  },
  {
    id: "common-tax",
    city: "common",
    category: "全国税收规则",
    title: "全国住房交易税收基线",
    summary: "契税优惠、2026 年个人销售住房增值税、满五唯一和个人住房零税项属于全国规则；计税价格、核定征收和申报结果仍由所在地税务机关确认。",
    table: {
      headers: ["项目", "条件", "税率/结果", "规则版本"],
      rows: [
        ["契税", "家庭唯一住房，面积 ≤140㎡", "1%", "NAT-TAX-DEED-001@2024-12-01.1"],
        ["契税", "家庭唯一住房，面积 >140㎡", "1.5%", "NAT-TAX-DEED-001@2024-12-01.1"],
        ["契税", "家庭第二套，面积 ≤140㎡", "1%", "NAT-TAX-DEED-001@2024-12-01.1"],
        ["契税", "家庭第二套，面积 >140㎡", "2%", "NAT-TAX-DEED-001@2024-12-01.1"],
        ["契税", "不符合以上优惠", "所在地一般税率 3%", "NAT-TAX-DEED-001@2024-12-01.1"],
        ["增值税", "卖方取得不足 2 年", "3% 征收率", "NAT-TAX-VAT-001@2026-01-01.1"],
        ["增值税", "卖方取得满 2 年", "免征", "NAT-TAX-VAT-001@2026-01-01.1"],
        ["个人所得税", "自用满 5 年且家庭唯一生活用房", "免征", "NAT-TAX-IIT-001@current.1"],
        ["满五唯一范围", "卖方与配偶在同一省、自治区或直辖市无其他住房", "满足唯一条件", "NAT-TAX-IIT-UNIQUE-001@current.1"],
        ["换购个税退税", "2026—2027 年同城卖旧后 1 年内买新且产权人符合", "新购额≥出售额全退，否则按金额比例退", "NAT-TAX-IIT-REFUND-001@2026-01-01.1"],
        ["印花税", "个人买卖住房", "暂免征收", "NAT-TAX-STAMP-001@current.1"],
        ["土地增值税", "个人销售住房", "暂免征收", "NAT-TAX-LAT-001@current.1"],
      ],
    },
    details: [
      "契税的家庭套数认定不能用贷款首套、二套认定替代。",
      "直辖市按本市范围核验满五唯一；其他城市按所在省范围，并同时核验卖方与配偶。",
      "换购退税属于卖方后续可申请款项，未到账前不得直接冲减交易时需准备的现金。",
      "增值税含税价换算和附加税额以当地税务申报系统为准。",
      "无法提供原值凭证时，由主管税务机关决定核定口径，不应跨城市统一硬编码 1%。",
    ],
    sources: nationalTaxSources,
    keywords: ["140㎡", "契税", "增值税", "满五唯一", "法定纳税人"],
  },
  {
    id: "common-cost",
    city: "common",
    category: "资金计算",
    title: "首付、现金需求与取得成本",
    summary: "合同价、计税价格和银行评估价必须分开。政策最低首付只是下限，不是银行最终批贷结果。",
    formula: [
      "政策最低首付 = 银行认可的贷款价值 × 政策最低首付比例",
      "实际首付 = 合同房价 − 实际获批贷款额",
      "交易时现金需求 = 实际首付 + 买方税费 + 代卖方承担税费 + 服务费及其他现金支出",
      "取得总成本 = 合同房价 + 全部非房价成本",
      "卖方核实征收个税 =（转让收入 − 房屋原值 − 税金 − 合理费用）× 20%",
      "换购退税（新购额 < 出售额）= 已缴住房个税 × 新购住房金额 ÷ 出售住房金额",
    ],
    details: [
      "卖方税费只有合同明确约定由买方承担时，才加入买方现金需求。",
      "退税、补贴等未来回款单列为潜在回收，不在实际到账前冲减成交现金。",
      "中介费、评估费和登记类费用使用实际报价，不静态写死。",
      "住宅不动产登记费国家标准为 80 元/件，但需核验登记事项、减免和当地实际收费后再计入。",
    ],
    keywords: ["现金需求", "取得成本", "合同价", "计税价", "银行评估价", "实际首付"],
  },
  {
    id: "common-examples",
    city: "common",
    category: "可复算示例",
    title: "两组资金结果对比",
    summary: "示例用于验收规则计算。所有金额均假设计税价和银行认可价值等于合同价，且银行按政策最低比例足额批贷。",
    table: {
      headers: ["场景", "北京", "深圳", "广州"],
      rows: [
        ["500万、100㎡、家庭唯一、卖方满五唯一、商贷首套", "最低现金 80万 + 未知费用", "最低现金 80万 + 未知费用", "最低现金 80万 + 未知费用"],
        ["800万、150㎡、家庭第二套、卖方满二不满五、各自承担法定税", "最低现金 176万 + 未知费用", "最低现金 176万 + 未知费用", "最低现金 136万 + 未知费用"],
        ["第二场景买方代付卖方 56万个税", "232万 + 未知费用", "232万 + 未知费用", "192万 + 未知费用"],
      ],
    },
    details: [
      "第一场景：契税 5 万，三城商贷首套最低首付均为 75 万。",
      "第二场景：契税 16 万；北京、深圳商贷二套最低首付 160 万，广州为 120 万。",
      "卖方个税 56 万只在合同约定买方代付时进入买方现金需求。",
    ],
    note: "具体房源仍需产权核验、银行授信和税务系统确认，因此可交易性与贷款资格保留 conditional。",
    keywords: ["500万", "800万", "80万", "176万", "136万", "示例"],
  },
  {
    id: "common-versions",
    city: "common",
    category: "政策版本",
    title: "政策演变与历史日期查询",
    summary: "知识库同时保存政策有效时间和知识记录时间。规则条件变化时新增版本，旧版本不可覆盖。",
    table: {
      headers: ["范围", "历史版本", "当前版本", "切换日期"],
      rows: [
        ["全国通则", "物化现行税费规则；完整历史包仍待扩展", "cn-tax@2026-07-16.1", "2026-07-16 决策快照"],
        ["北京", "bj@2025-08-09.1", "bj@2025-12-24.1", "2025-12-24"],
        ["深圳", "sz@2025-09-06.1", "sz@2026-04-30.1", "2026-04-30"],
        ["广州", "gz@2024-05-29.1", "gz@2024-09-30.1", "2024-09-30"],
        ["上海", "更早完整包未物化", "sh@2026-02-26.1", "2026-02-26"],
        ["天津", "不限购基线自 2024-10-16", "tj@2026-02-01.1", "2026-02-01"],
        ["武汉", "不限购基线自 2023-09-19", "wh@2025-09-30.1", "2025-09-30"],
        ["杭州", "不限购基线自 2024-05-09", "hz@2024-10-09.1", "2024-10-09"],
        ["苏州", "一般限售取消自 2025-08-27", "su@2026-06-01.1", "2026-06-01"],
        ["成都", "不限购基线自 2024-04-29", "cd@2026-03-25.1", "2026-03-25"],
        ["重庆", "房产税调整基线自 2025-01-01", "cq@2026-02-09.1", "2026-02-09"],
        ["西安", "不限购基线自 2024-05-09", "xa@2025-07-31.1", "2025-07-31"],
        ["南京", "不限购基线自 2023-09-08", "nj@2026-04-16.1", "2026-04-16"],
        ["全国住房增值税", "更早版本未物化", "NAT-TAX-VAT-001@2026-01-01.1", "2026-01-01"],
        ["换购住房个税退税", "2024—2025 延续期", "NAT-TAX-IIT-REFUND-001@2026-01-01.1", "2026-01-01"],
        ["满五唯一地域范围", "仅保存现行口径", "NAT-TAX-IIT-UNIQUE-001@current.1", "current-only"],
      ],
    },
    details: [
      "历史查询采用 effective_from ≤ query_date < effective_to。",
      "查询日期早于已登记覆盖范围时返回 unknown，不用现行规则倒推。",
      "全国知识包日期是知识快照，不是民法典、登记费或信贷政策共同的生效日；每个规则族保留自身有效区间。",
      "城市政策包没有因本次全国补全而伪造新生效日；全国与共享知识族独立增加版本。",
      "一次发布使用 kb_release 整体回滚；当前发布为 2026.07.16-decision-r1。",
    ],
    keywords: ["版本", "历史政策", "effective_from", "回滚", "政策演变"],
  },
  {
    id: "common-monitoring",
    city: "common",
    category: "实时更新",
    title: "官方来源监测与审核发布",
    summary: "知识库采用近实时监测而不是未经审核的自动改规则：P0 来源每 6 小时检查，P1 来源每 24 小时检查。",
    table: {
      headers: ["状态", "含义", "Agent 行为"],
      rows: [
        ["fresh", "来源在时效目标内且内容未变化", "正常执行已发布规则"],
        ["stale", "超过 24 小时未核验", "显示新鲜度警告"],
        ["changed_pending_review", "官方页面指纹发生变化", "受影响主题返回 unknown/needs_review"],
        ["error", "来源检查失败", "保留审计信息并提示人工核验"],
        ["baseline_pending", "监测尚未建立完整远端基线", "不得宣称实时已核验"],
      ],
    },
    details: [
      "监测器对官方页面规范化可见文本计算 SHA-256，变化进入人工审核队列。",
      "完成条款影响分析、规则更新、黄金用例和人工审核后，才生成新发布版本。",
      "当前接入 57 个监测入口，覆盖全国与 12 城核心购房、贷款、公积金、特殊产权和本地房产税来源；后台定时调度尚未启用。",
    ],
    note: "高风险政策知识不自动发布，是为了避免官网布局变化、旧文案残留或解释文件更新造成错误结论。",
    keywords: ["实时更新", "监测", "6小时", "24小时", "pending_review", "新鲜度"],
  },
];

export const cityNames: Record<CityKey, string> = {
  beijing: "北京",
  shenzhen: "深圳",
  guangzhou: "广州",
  shanghai: "上海",
  tianjin: "天津",
  wuhan: "武汉",
  hangzhou: "杭州",
  suzhou: "苏州",
  chengdu: "成都",
  chongqing: "重庆",
  xian: "西安",
  nanjing: "南京",
  common: "全国通则",
};
